### ISSUE TITLE
Connection diagram WS2815 to Pico

### ISSUE THREAD

**Issue by 2m** [krzmaz/pico-w-neopixel-server#7]
I am building `rustmas` christmas lights and was not able to find how the WS2815 LED strip should be connected to Pico. Is it possible to control WS2815 LED strip with pico-w-neopixel-server?

Such LED strip has four wires: VCC, GND, Green data line and Blue backup line.

**Comment by krzmaz** [comment]
Hi, great to see someone using Rustmas! 😁 
As for the connection: the pin on which the Raspberry Pi Pico sends the data is set here: https://github.com/krzmaz/pico-w-neopixel-server/blob/main/src/bin/tcp.rs#L58 and is currently hardcoded to GPIO2.

As for WS2815 lights - I haven't used them personally, but according to [some info I've found](https://wled.discourse.group/t/wiring-of-ws2815-question/5626/6) it seems that you should connect your strips data line to GPIO2 and backup line to GND.
Also, make sure that the GNDs on the Pico and LEDs are connected.
I don't know how experienced you are with electronics, so if you have any further questions, feel free to ask! 😄
